### ISSUE TITLE
How to run in windows.

### ISSUE THREAD

**Issue by sjanapro** [facebookresearch/nougat#107]
nougat is not recognised in the cmd after installing..

**Comment by lukas-blecher** [comment]
It should be. How did you install it?
Make sure you activate the environment before calling nougat.

**Comment by sjanapro** [comment]
Using pip and I am not using any environment.

**Comment by sjanapro** [comment]
There is no virtual environment. I just installed the package and it's dependencies then tried to run it from cmd but it is showing the error as I mentioned earlier.

**Comment by gelprec** [comment]
I didn't manage to make nougat work either (on windows 11). When installing with pip everything went ok. Maybe it's just a stupid mistake on my part. I found a nougat.exe file inside some python folder and ran it here using a powershell console getting the message below

```
PS C:\Users\geo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts> .\nougat -h
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\geo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\nougat.exe\__main__.py", line 4, in <module>
  File "C:\Users\geo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\predict.py", line 17, in <module>
    from nougat import NougatModel
  File "C:\Users\geo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nougat\__init__.py", line 8, in <module>
    from .utils.dataset import NougatDataset
  File "C:\Users\geo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nougat\utils\dataset.py", line 21, in <module>
    from nougat.dataset.rasterize import rasterize_paper
  File "C:\Users\geo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nougat\dataset\rasterize.py", line 18, in <module>
    pdf: Path | bytes,
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by gelprec** [comment]
Thanks. I uninstalled python 3.9 and installed the newer version 3.11.5. I reinstalled nougat and it works, but the default CPU version is very slow (about 3 minutes for two pages pdf), hence it's necessary to install a gpu/cuda aware torch version. I followed these steps 
* Uninstall the previous torch version (`pip uninstall torch`)
* Go to https://pytorch.org/get-started/locally/ where is a command generator and see there that the recommended/default cuda version is CUDA 11.7. 
* I go to the https://developer.nvidia.com/cuda-toolkit-archive and choose here that older version 11.7 and install it (it's a big package, almost 3 giga)
* Execute finally the command suggested/generated at https://pytorch.org/get-started/locally/

Now the process is much speedier and the resulted ocr seems very accurate, better than I expected.

**Comment by zf0x00** [comment]
I am still getting this on python 11

**Comment by soul667** [comment]
you should better use docker
```dockerfile
FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/pytorch/pytorch:2.4.1-cuda12.4-cudnn9-runtime
RUN apt-get update
RUN mkdir workspace
WORKDIR /workspace
# RUN pipx ensurepath
RUN pip3 install nougat-ocr -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install fastapi -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install transformers==4.38.2 
```
