### ISSUE TITLE
module 'albumentations' has no attribute 'Affine'. Did you mean: 'IAAAffine'?

### ISSUE THREAD

**Issue by lookou** [facebookresearch/nougat#12]
Macbook pro M1 Max  OS: Ventuna 13.4

 install cmd:
`pip3.10 install git+https://github.com/facebookresearch/nougat `

get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/nougat", line 5, in <module>
    from predict import main
  File "/usr/local/lib/python3.10/site-packages/predict.py", line 17, in <module>
    from nougat import NougatModel
  File "/usr/local/lib/python3.10/site-packages/nougat/__init__.py", line 7, in <module>
    from .model import NougatConfig, NougatModel
  File "/usr/local/lib/python3.10/site-packages/nougat/model.py", line 34, in <module>
    from nougat.transforms import train_transform, test_transform
  File "/usr/local/lib/python3.10/site-packages/nougat/transforms.py", line 74, in <module>
    alb.Affine(shear={"x": (0, 3), "y": (-3, 0)}, cval=(255, 255, 255), p=0.03),
AttributeError: module 'albumentations' has no attribute 'Affine'. Did you mean: 'IAAAffine'?
```

**Comment by lukas-blecher** [comment]
From the albumentations doc I got this:
> This augmentation is deprecated. Please use Affine instead

[source](https://albumentations.ai/docs/api_reference/full_reference/#albumentations.imgaug.transforms.IAAAffine)
Try updating the package
