### ISSUE TITLE
get type error from running sklearn.externals.joblib.externals import cloudpickle

### ISSUE THREAD

**Issue by JKYang01** [facebookresearch/nougat#203]
This is the command I tried on my terminal:
 `nougat ./TPG_HSBC_1.pdf -o ./`
 
the flowing the error message I don't know what is happening there

Traceback (most recent call last):
  File "/home/bluespinach/miniconda3/envs/tf2/bin/nougat", line 5, in <module>
    from predict import main
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/predict.py", line 18, in <module>
    from nougat import NougatModel
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/nougat/__init__.py", line 7, in <module>
    from .model import NougatConfig, NougatModel
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/nougat/model.py", line 33, in <module>
    from nougat.postprocessing import postprocess
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/nougat/postprocessing.py", line 11, in <module>
    from nltk.corpus import words
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/nltk/__init__.py", line 145, in <module>
    from nltk.chunk import *
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/nltk/chunk/__init__.py", line 155, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.chunk.util import ChunkScore
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/nltk/chunk/util.py", line 12, in <module>
    from nltk.tag.mapping import map_tag
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/nltk/tag/__init__.py", line 70, in <module>
    from nltk.tag.sequential import (
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/nltk/tag/sequential.py", line 26, in <module>
    from nltk.classify import NaiveBayesClassifier
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/nltk/classify/__init__.py", line 97, in <module>
    from nltk.classify.scikitlearn import SklearnClassifier
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/nltk/classify/scikitlearn.py", line 38, in <module>
    from sklearn.feature_extraction import DictVectorizer
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/base.py", line 14, in <module>
    from .utils.fixes import signature
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/utils/__init__.py", line 14, in <module>
    from . import _joblib
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/utils/_joblib.py", line 22, in <module>
    from ..externals import joblib
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/externals/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/externals/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/externals/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/externals/joblib/externals/loky/__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/externals/joblib/externals/loky/backend/reduction.py", line 125, in <module>
    from sklearn.externals.joblib.externals import cloudpickle  # noqa: F401
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/externals/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 152, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/bluespinach/miniconda3/envs/tf2/lib/python3.9/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 133, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)

**Comment by JKYang01** [comment]
is this error caused the python version?

**Comment by JKYang01** [comment]
is this error caused by the python version?
