### ISSUE TITLE
Please add Rocm support

### ISSUE THREAD

**Issue by sirus20x6** [facebookresearch/nougat#220]
WARNING:root:No GPU found. Conversion on CPU is very slow.

I would appreciate ROCM support. I don't have an nvidia gpu

**Comment by sirus20x6** [comment]
```
(venv) (base) neuromancer :) > nougat
Traceback (most recent call last):
  File "/thearray/git/thegreatcaper/venv/bin/nougat", line 5, in <module>
    from predict import main
  File "/thearray/git/thegreatcaper/venv/lib/python3.12/site-packages/predict.py", line 18, in <module>
    from nougat import NougatModel
  File "/thearray/git/thegreatcaper/venv/lib/python3.12/site-packages/nougat/__init__.py", line 7, in <module>
    from .model import NougatConfig, NougatModel
  File "/thearray/git/thegreatcaper/venv/lib/python3.12/site-packages/nougat/model.py", line 17, in <module>
    import timm
  File "/thearray/git/thegreatcaper/venv/lib/python3.12/site-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/thearray/git/thegreatcaper/venv/lib/python3.12/site-packages/timm/models/__init__.py", line 1, in <module>
    from .beit import *
  File "/thearray/git/thegreatcaper/venv/lib/python3.12/site-packages/timm/models/beit.py", line 29, in <module>
    from .helpers import build_model_with_cfg
  File "/thearray/git/thegreatcaper/venv/lib/python3.12/site-packages/timm/models/helpers.py", line 17, in <module>
    from .fx_features import FeatureGraphNet
  File "/thearray/git/thegreatcaper/venv/lib/python3.12/site-packages/timm/models/fx_features.py", line 10, in <module>
    from torchvision.models.feature_extraction import create_feature_extractor
  File "/thearray/git/thegreatcaper/venv/lib/python3.12/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/thearray/git/thegreatcaper/venv/lib/python3.12/site-packages/torchvision/_meta_registrations.py", line 163, in <module>
    @torch._custom_ops.impl_abstract("torchvision::nms")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/thearray/git/thegreatcaper/venv/lib/python3.12/site-packages/torch/library.py", line 467, in inner
    handle = entry.abstract_impl.register(func_to_register, source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/thearray/git/thegreatcaper/venv/lib/python3.12/site-packages/torch/_library/abstract_impl.py", line 30, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: operator torchvision::nms does not exist

```

```
(venv) (base) neuromancer :) > pip show torchvision
Name: torchvision
Version: 0.18.0
Summary: image and video datasets and models for torch deep learning
Home-page: https://github.com/pytorch/vision
Author: PyTorch Core Team
Author-email: soumith@pytorch.org
License: BSD
Location: /thearray/git/thegreatcaper/venv/lib/python3.12/site-packages
Requires: numpy, pillow, torch
Required-by: timm
(venv) (base) neuromancer :) > pip show torch
Name: torch
Version: 2.3.0+rocm6.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /thearray/git/thegreatcaper/venv/lib/python3.12/site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: lightning, pytorch-lightning, timm, torchaudio, torchmetrics, torchvision

```
