### ISSUE TITLE
Why can't I run nougat-ocr on pdfs?

### ISSUE THREAD

**Issue by emilyhanyf** [facebookresearch/nougat#226]
`ImportError: cannot import name 'cached_property' from 'nougat.utils' (/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/utils/__init__.py)
OCRing with base model failed on /lfs/skampere1/0/emilyhyf/massive-evaporation-4-math/data/debug_pdfs/dummy_folder1/The_IMO_Compendium.pdf... trying small model
Traceback (most recent call last):
  File "/lfs/skampere1/0/emilyhyf/miniconda/bin/nougat", line 5, in <module>
    from predict import main
  File "/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/predict.py", line 18, in <module>
    from nougat import NougatModel
  File "/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/__init__.py", line 1, in <module>
    from nougat.app import Nougat
  File "/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/app.py", line 5, in <module>
    from nougat.asgi import serve
  File "/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/asgi.py", line 6, in <module>
    from nougat.context.request import Request
  File "/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/context/__init__.py", line 1, in <module>
    from nougat.context.request import Request
  File "/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/context/request.py", line 8, in <module>
    from nougat.utils import cached_property, File
ImportError: cannot import name 'cached_property' from 'nougat.utils' (/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/utils/__init__.py)
OCRing with small model failed on /lfs/skampere1/0/emilyhyf/massive-evaporation-4-math/data/debug_pdfs/dummy_folder1/The_IMO_Compendium.pdf
The following files failed OCRing and need manual review:
/lfs/skampere1/0/emilyhyf/massive-evaporation-4-math/data/debug_pdfs/putnam_and_beyond.pdf
/lfs/skampere1/0/emilyhyf/massive-evaporation-4-math/data/debug_pdfs/dummy_folder1/The_IMO_Compendium.pdf
Time taken: 8.497612476348877 seconds, 0.1416268746058146 minutes, 0.00236044791009691 hours`

**Comment by ivanmladek** [comment]
same error

**Comment by hqy479** [comment]
same error

**Comment by hqy479** [comment]
nougat.utils init file is empty， i don‘t know why

**Comment by Jawwadabd** [comment]
anyone found solution to this? @ivanmladek @hqy479 @emilyhanyf @Celebio @nlutsenko

**Comment by lemorage** [comment]
> `ImportError: cannot import name 'cached_property' from 'nougat.utils' (/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/utils/__init__.py) OCRing with base model failed on /lfs/skampere1/0/emilyhyf/massive-evaporation-4-math/data/debug_pdfs/dummy_folder1/The_IMO_Compendium.pdf... trying small model Traceback (most recent call last): File "/lfs/skampere1/0/emilyhyf/miniconda/bin/nougat", line 5, in <module> from predict import main File "/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/predict.py", line 18, in <module> from nougat import NougatModel File "/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/__init__.py", line 1, in <module> from nougat.app import Nougat File "/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/app.py", line 5, in <module> from nougat.asgi import serve File "/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/asgi.py", line 6, in <module> from nougat.context.request import Request File "/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/context/__init__.py", line 1, in <module> from nougat.context.request import Request File "/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/context/request.py", line 8, in <module> from nougat.utils import cached_property, File ImportError: cannot import name 'cached_property' from 'nougat.utils' (/lfs/skampere1/0/emilyhyf/miniconda/lib/python3.12/site-packages/nougat/utils/__init__.py) OCRing with small model failed on /lfs/skampere1/0/emilyhyf/massive-evaporation-4-math/data/debug_pdfs/dummy_folder1/The_IMO_Compendium.pdf The following files failed OCRing and need manual review: /lfs/skampere1/0/emilyhyf/massive-evaporation-4-math/data/debug_pdfs/putnam_and_beyond.pdf /lfs/skampere1/0/emilyhyf/massive-evaporation-4-math/data/debug_pdfs/dummy_folder1/The_IMO_Compendium.pdf Time taken: 8.497612476348877 seconds, 0.1416268746058146 minutes, 0.00236044791009691 hours`

From the above error msg, I could see the attempt to import something from the path `nougat/context/`, however, in this [Nougat](https://github.com/facebookresearch/nougat/tree/main/nougat) package, there is no `context` directory at all. So I am very suspicious you're importing the wrong package. Based on this thread of thought, I found this package (https://github.com/Riparo/nougat), with the same name "Nougat". Likely, you're actually using this package behind the scenes, since I could see the usage of "cached_property" > [here](https://github.com/Riparo/nougat/blob/master/nougat/utils.py#L62).

So my end solution is to do `pip uninstall nougat` and `pip install nougat-ocr` to specify the correct package.
