### ISSUE TITLE
TypeError: BARTDecoder.prepare_inputs_for_inference() got an unexpected keyword argument 'cache_position'

### ISSUE THREAD

**Issue by hongyi-zhao** [facebookresearch/nougat#228]
On Ubuntu 22.04.4 LTS, I tried to use nougat as follows but failed:

```shell
$ pyenv shell datasci
(datasci) werner@x13dai-t:~$ cd "/home/werner/Public/repo/github.com/facebookresearch/nougat.git" && pip install -e .
(datasci) werner@x13dai-t:~$ nougat 'Public/hpc/servers/gpu/多种平台运行VASP、Quantum Espresso、Lammps和DeePMD-kit的性能测试/扫描全能王 2024-06-11 16.30.pdf' -o .
/home/werner/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/home/werner/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                                                                                                           | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/bin/nougat", line 33, in <module>
    sys.exit(load_entry_point('nougat-ocr', 'console_scripts', 'nougat')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/facebookresearch/nougat.git/predict.py", line 167, in main
    model_output = model.inference(
                   ^^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/facebookresearch/nougat.git/nougat/model.py", line 592, in inference
    decoder_output = self.decoder.model.generate(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/transformers/generation/utils.py", line 1758, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/transformers/generation/utils.py", line 2394, in _sample
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BARTDecoder.prepare_inputs_for_inference() got an unexpected keyword argument 'cache_position'
```

Regards,
Zhao

**Comment by sparsh35** [comment]
Try to downgrade to transformers 4.38.2 , I believe Transformers introduced this cache position somewhere around , 4.39.0 etc

**Comment by hongyi-zhao** [comment]
This really fixed the problem reported here, but the result file generated by nougat is empty in my test, as shown below:

```shell
$ proxychains-ng-country-control uv pip install transformers==4.38.2
$ nougat 扫描全能王-2024-06-11-16.30.pdf -o .
/home/werner/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/home/werner/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                                                                                                           | 0/1 [00:00<?, ?it/s][nltk_data] Error loading words: <urlopen error [Errno 111] Connection
[nltk_data]     refused>
INFO:root:Processing file 扫描全能王-2024-06-11-16.30.pdf with 1 pages
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.44it/s]

$ cat 扫描全能王-2024-06-11-16.30.mmd
$ 
```
[扫描全能王-2024-06-11-16.30.zip](https://github.com/user-attachments/files/15844699/-2024-06-11-16.30.zip)

Regards,
Zhao

**Comment by sparsh35** [comment]
try   --no-skipping as argument in the command like this 

nougat 扫描全能王-2024-06-11-16.30.pdf -o . -m 0.1.0-base --no-skipping

**Comment by hongyi-zhao** [comment]
Still useless, as shown below:

```shell
(datasci) werner@x13dai-t:~$ proxychains-ng-country-control nougat 扫描全能王-2024-06-11-16.30.pdf -o . -m 0.1.0-base --no-skipping
/home/werner/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/home/werner/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                                                         | 0/1 [00:00<?, ?it/s]INFO:root:Processing file 扫描全能王-2024-06-11-16.30.pdf with 1 pages
100%|█████████████████████████████████████████████████████████████████████████████████| 1/1 [00:17<00:00, 17.27s/it]

(datasci) werner@x13dai-t:~$ cat 扫描全能王-2024-06-11-16.30.mmd
\(\frac{1}{2}\).

## 5. Conclusion

In this paper, we have proposed a new method for the estimation of the \(\frac{1}{2}
```

[扫描全能王-2024-06-11-16.30.mmd.zip](https://github.com/user-attachments/files/15846300/-2024-06-11-16.30.mmd.zip)

**Comment by sparsh35** [comment]
is original pdf also 1 page

**Comment by hongyi-zhao** [comment]
> is original pdf also 1 page

Yes.

**Comment by sparsh35** [comment]
yeah it is not full proof , if you have very less work to convert , I would suggest using Mathpix , it gives I think 10 pdf conversions, and much more accurate.

**Comment by sparsh35** [comment]
That's why it is not working , it is trained on arxiv research papers data , it is out of domain for this model.

**Comment by hongyi-zhao** [comment]
I tried Mathpix, but the results were equally unsatisfactory.

**Comment by ivanmladek** [comment]
pip install transformers==4.38.2 pyarrow==14.0.1 requests==2.31.0 git+https://github.com/facebookresearch/nougat

**Comment by hongyi-zhao** [comment]
@ivanmladek What do you mean? This will solve this issue here?

**Comment by larsschwarz** [comment]
Downgrading transformers from 4.44.2 to 4.38.2 did work fine for me and fixed the cache_position error
