### ISSUE TITLE
pydantic error

### ISSUE THREAD

**Issue by breisfeld** [facebookresearch/nougat#232]
Hi, When running `nougat` on a test pdf file

```
$ nougat /Users/XXXXX/Downloads/pharmaceutics-16-00226.pdf -o output
```
I get the following traceback:

```
Traceback (most recent call last):
  File "/Users/XXXXX/miniconda3/envs/extract_pdf_tables/bin/nougat", line 5, in <module>
    from predict import main
  File "/Users/XXXXX/miniconda3/envs/extract_pdf_tables/lib/python3.12/site-packages/predict.py", line 18, in <module>
    from nougat import NougatModel
  File "/Users/XXXXX/miniconda3/envs/extract_pdf_tables/lib/python3.12/site-packages/nougat/__init__.py", line 7, in <module>
    from .model import NougatConfig, NougatModel
  File "/Users/XXXXX/miniconda3/envs/extract_pdf_tables/lib/python3.12/site-packages/nougat/model.py", line 34, in <module>
    from nougat.transforms import train_transform, test_transform
  File "/Users/XXXXX/miniconda3/envs/extract_pdf_tables/lib/python3.12/site-packages/nougat/transforms.py", line 146, in <module>
    alb.ElasticTransform(
  File "/Users/XXXXX/miniconda3/envs/extract_pdf_tables/lib/python3.12/site-packages/albumentations/core/validation.py", line 35, in custom_init
    config = dct["InitSchema"](**full_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXXXX/miniconda3/envs/extract_pdf_tables/lib/python3.12/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for InitSchema
alpha_affine
  Input should be None [type=none_required, input_value=1.2, input_type=float]
    For further information visit https://errors.pydantic.dev/2.8/v/none_required
```

I get the same traceback when running `nougat` with no arguments.

I have tried running this same command under MacOS, Linux, and Windows.
On all platforms, `nougat` was installed into a fresh `conda` virtual environment using `pip`.

Any advice on solving the problem?

Thanks.

**Comment by YuCheng-Qi** [comment]
Modify alb.ElasticTransform( p=1, alpha=50, sigma=120 * 0.1, alpha_affine=120 * 0.01, border_mode=0, value=(255, 255, 255), ), to alb.ElasticTransform in transforms.py (p=1, alpha=50, sigma=120 * 0.1, alpha_affine=None, border_mode=0, value=(255, 255, 255), ),

**Comment by YuCheng-Qi** [comment]
@breisfeld

**Comment by eesyfep** [comment]
> mode
Even I changed the parameters, it shows the same warning

**Comment by YodaGitMaster** [comment]
Thanks

**Comment by e-hossam96** [comment]
> Modify alb.ElasticTransform( p=1, alpha=50, sigma=120 * 0.1, alpha_affine=120 * 0.01, border_mode=0, value=(255, 255, 255), ), to alb.ElasticTransform in transforms.py (p=1, alpha=50, sigma=120 * 0.1, alpha_affine=None, border_mode=0, value=(255, 255, 255), ),

Worked for me too. Thanks!

**Comment by SichangHe** [comment]
Can't even make a PR to fix this lol. They locked it down to collaborator-only.

**Comment by samiahhassan** [comment]
I am having the same issues with nougat. I am new to OCR. Please assist me with where I should make the change for the ElasticTransform function or any other way. Thanks for any advice.

> Modify alb.ElasticTransform( p=1, alpha=50, sigma=120 * 0.1, alpha_affine=120 * 0.01, border_mode=0, value=(255, 255, 255), ), to alb.ElasticTransform in transforms.py (p=1, alpha=50, sigma=120 * 0.1, alpha_affine=None, border_mode=0, value=(255, 255, 255), ),

**Comment by anshumankmr** [comment]
Getting some strange error after making that edit, 
>No module named nougat.__main__; 'nougat' is a package and cannot be directly executed

Windows 11

**Comment by snimavat** [comment]
Same error, Macbook pro Python 3.11.2

**Comment by dimazig** [comment]
same issue 
```
Traceback (most recent call last):
  File "/home/dima/nougat/bin/nougat", line 5, in <module>
    from predict import main
  File "/home/dima/nougat/lib/python3.12/site-packages/predict.py", line 18, in <module>
    from nougat import NougatModel
  File "/home/dima/nougat/lib/python3.12/site-packages/nougat/__init__.py", line 7, in <module>
    from .model import NougatConfig, NougatModel
  File "/home/dima/nougat/lib/python3.12/site-packages/nougat/model.py", line 34, in <module>
    from nougat.transforms import train_transform, test_transform
  File "/home/dima/nougat/lib/python3.12/site-packages/nougat/transforms.py", line 146, in <module>
    alb.ElasticTransform(
  File "/home/dima/nougat/lib/python3.12/site-packages/albumentations/core/validation.py", line 35, in custom_init
    config = dct["InitSchema"](**full_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dima/nougat/lib/python3.12/site-packages/pydantic/main.py", line 209, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for InitSchema
alpha_affine
  Input should be None [type=none_required, input_value=1.2, input_type=float]
    For further information visit https://errors.pydantic.dev/2.9/v/none_required

```

**Comment by Fireblossom** [comment]
`pip install albumentations==1.4.8`

**Comment by breisfeld** [comment]
> `pip install albumentations==1.4.8`

@SichangHe , should the existing line in `setup.py` be replaced by this if it is the true dependency?

**Comment by SichangHe** [comment]
> > `pip install albumentations==1.4.8`
> 
> @SichangHe , should the existing line in `setup.py` in your fork be replaced by this if it is the true dependency?

I doublechecked, I have 1.4.14 in my environment and it still works.

Also, I am moving away to marker-pdf because it seems to give fewer spurious errors, although their header detection and math decoding really suck.

**Comment by anshumankmr** [comment]
Instead of calling the nougat thing via the CLI, I chose to install nougat_api and it worked for me. That was sufficient for my use case.
