### ISSUE TITLE
 Input should be None [type=none_required, input_value=1.2, input_type=float]     For further information visit https://errors.pydantic.dev/2.8/v/none_required

### ISSUE THREAD

**Issue by cherryGQR** [facebookresearch/nougat#243]
Traceback (most recent call last):
  File "/home/cherrygump/anaconda3/envs/nougat/bin/nougat", line 5, in <module>
    from predict import main
  File "/home/cherrygump/anaconda3/envs/nougat/lib/python3.10/site-packages/predict.py", line 18, in <module>
    from nougat import NougatModel
  File "/home/cherrygump/anaconda3/envs/nougat/lib/python3.10/site-packages/nougat/__init__.py", line 7, in <module>
    from .model import NougatConfig, NougatModel
  File "/home/cherrygump/anaconda3/envs/nougat/lib/python3.10/site-packages/nougat/model.py", line 34, in <module>
    from nougat.transforms import train_transform, test_transform
  File "/home/cherrygump/anaconda3/envs/nougat/lib/python3.10/site-packages/nougat/transforms.py", line 146, in <module>
    alb.ElasticTransform(
  File "/home/cherrygump/anaconda3/envs/nougat/lib/python3.10/site-packages/albumentations/core/validation.py", line 35, in custom_init
    config = dct["InitSchema"](**full_kwargs)
  File "/home/cherrygump/anaconda3/envs/nougat/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for InitSchema
alpha_affine
  Input should be None [type=none_required, input_value=1.2, input_type=float]
    For further information visit https://errors.pydantic.dev/2.8/v/none_required

**Comment by ptrckSTL** [comment]
Seeing this as well on a fresh install

**Comment by anshumankmr** [comment]
How to resolve this?

**Comment by armancohan** [comment]
downgrade albumentations
`pip install albumentations==1.0.0`

**Comment by seetimee** [comment]
> downgrade albumentations `pip install albumentations==1.0.0`

thanks
