### ISSUE TITLE
load error with the current pretrained model

### ISSUE THREAD

**Issue by FanqingM** [facebookresearch/nougat#34]
When I use the current pretrained model from small version in https://github.com/facebookresearch/nougat/releases, I get thie error:
Traceback (most recent call last):
  File "/home/mengfanqing/nougat-0.1.0-small/train.py", line 208, in <module>
    train(config)
  File "/home/mengfanqing/nougat-0.1.0-small/train.py", line 182, in train
    trainer.fit(model_module, data_module, ckpt_path=config.get("resume_from_checkpoint_path", None))
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 946, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 399, in _restore_modules_and_callbacks
    self.resume_start(checkpoint_path)
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 84, in resume_start
    self._loaded_checkpoint = _pl_migrate_checkpoint(loaded_checkpoint, checkpoint_path)
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/utilities/migration/utils.py", line 142, in _pl_migrate_checkpoint
    old_version = _get_version(checkpoint)
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/utilities/migration/utils.py", line 163, in _get_version
    return checkpoint["pytorch-lightning_version"]
KeyError: 'pytorch-lightning_version'

This is mt environment: packages in environment at /home/mengfanqing/anaconda3/envs/naugat_official:
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
aiohttp                   3.8.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
albumentations            1.3.1                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.05.30           h06a4308_0  
certifi                   2023.7.22                pypi_0    pypi
charset-normalizer        3.2.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cmake                     3.27.2                   pypi_0    pypi
datasets                  2.14.4                   pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
filelock                  3.12.3                   pypi_0    pypi
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.9.0                 pypi_0    pypi
huggingface-hub           0.16.4                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.31.3                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
lazy-loader               0.3                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
levenshtein               0.21.1                   pypi_0    pypi
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
lightning-utilities       0.9.0                    pypi_0    pypi
lit                       16.0.6                   pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.15                  pypi_0    pypi
munch                     4.0.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.1                      pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
nougat-ocr                0.1.0                    pypi_0    pypi
numpy                     1.25.2                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
opencv-python-headless    4.8.0.76                 pypi_0    pypi
openssl                   3.0.10               h7f8727e_2  
orjson                    3.9.5                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.1.0                    pypi_0    pypi
pillow                    10.0.0                   pypi_0    pypi
pip                       23.2.1          py310h06a4308_0  
pyarrow                   13.0.0                   pypi_0    pypi
pymupdf                   1.23.3                   pypi_0    pypi
pymupdfb                  1.23.3                   pypi_0    pypi
python                    3.10.12              h955ad1f_0  
python-dateutil           2.8.2                    pypi_0    pypi
python-levenshtein        0.21.1                   pypi_0    pypi
pytorch-lightning         2.0.8                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
qudida                    0.0.4                    pypi_0    pypi
rapidfuzz                 3.2.0                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
regex                     2023.8.8                 pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
ruamel-yaml               0.17.32                  pypi_0    pypi
ruamel-yaml-clib          0.2.7                    pypi_0    pypi
scikit-image              0.21.0                   pypi_0    pypi
scikit-learn              1.3.0                    pypi_0    pypi
scipy                     1.11.2                   pypi_0    pypi
sconf                     0.2.5                    pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
setuptools                68.0.0          py310h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
sympy                     1.12                     pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tifffile                  2023.8.30                pypi_0    pypi
timm                      0.5.4                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.3                   pypi_0    pypi
torch                     2.0.1                    pypi_0    pypi
torchmetrics              1.1.1                    pypi_0    pypi
torchvision               0.15.2                   pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
transformers              4.25.1                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
urllib3                   2.0.4                    pypi_0    pypi
wheel                     0.38.4          py310h06a4308_0  
xxhash                    3.3.0                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
yarl                      1.9.2                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  

I just fix the item in config/train_config.yml: resume_from_checkpoint_path: '/home/mengfanqing/nougat-0.1.0-small/model/pytorch_model.bin', which is in small version in https://github.com/facebookresearch/nougat/releases. I wonder if there exists some error with the ckp?

**Comment by FanqingM** [comment]
I just add state_dict['pytorch-lightning_version'] = "2.0.0" in this pytorch_model.bin, Then I got error: 
Traceback (most recent call last):
  File "/home/mengfanqing/nougat-0.1.0-small/train.py", line 208, in <module>
    train(config)
  File "/home/mengfanqing/nougat-0.1.0-small/train.py", line 182, in train
    trainer.fit(model_module, data_module, ckpt_path=config.get("resume_from_checkpoint_path", None))
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 971, in _run
    self._checkpoint_connector.restore_training_state()
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 300, in restore_training_state
    self.restore_optimizers_and_schedulers()
  File "/home/mengfanqing/anaconda3/envs/naugat_official/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 366, in restore_optimizers_and_schedulers
    raise KeyError(
KeyError: 'Trying to restore optimizer state but checkpoint contains only the model. This is probably due to `ModelCheckpoint.save_weights_only` being set to `True`.'

### How can I fix it?

**Comment by FanqingM** [comment]
Sorry, I just fix my problem with edit the model_path and do not edit the resume_from_checkpoint_path
