### ISSUE TITLE
 KeyError:'SLURM_NODEID'

### ISSUE THREAD

**Issue by gk966988** [facebookresearch/nougat#46]
**When I run `python train.py --config config/train_nougat.yaml,` I will report the following error:**

> Traceback (most recent call last):
  File "train.py", line 220, in <module>
    train(config)
  File "train.py", line 173, in train
    trainer = pl.Trainer(
  File "/root/miniconda3/envs/test_38/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 348, in insert_env_defaults
    return fn(self, **kwargs)
  File "/root/miniconda3/envs/test_38/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 419, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/root/miniconda3/envs/test_38/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 221, in __init__
    self._lazy_init_strategy()
  File "/root/miniconda3/envs/test_38/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 828, in _lazy_init_strategy
    self.strategy.set_world_ranks()
  File "/root/miniconda3/envs/test_38/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 211, in set_world_ranks
    self.cluster_environment.set_global_rank(self.node_rank * self.num_processes + self.local_rank)
  File "/root/miniconda3/envs/test_38/lib/python3.8/site-packages/pytorch_lightning/strategies/parallel.py", line 60, in node_rank
    return self.cluster_environment.node_rank() if self.cluster_environment is not None else 0
  File "/root/miniconda3/envs/test_38/lib/python3.8/site-packages/lightning_fabric/plugins/environments/slurm.py", line 136, in node_rank
    return int(os.environ["SLURM_NODEID"])
  File "/root/miniconda3/envs/test_38/lib/python3.8/os.py", line 673, in __getitem__
    raise KeyError(key) from None
KeyError: 'SLURM_NODEID'

**Why does this problem arise? Do you have any other special settings？**

**Comment by lukas-blecher** [comment]
I only ever trained in a slurm environment.  Comment out L185. 
I'll also push it to main in a bit
