### ISSUE TITLE
[Nougat version mismatch problem?] size mismatch for encoder.model.layers

### ISSUE THREAD

**Issue by binary-husky** [facebookresearch/nougat#62]
Hello, I have successfully intergrated nougat with GPT-Academic project. However, the users found a parameter mismatch problem in a PDF.

With some debugging trick, I can reproduce this problem under nougat-ocr == 0.1.5

```
/usr/local/lib/python3.8/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/usr/local/bin/nougat", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/predict.py", line 90, in main
    model = NougatModel.from_pretrained(args.checkpoint).to(torch.bfloat16)
  File "/usr/local/lib/python3.8/dist-packages/nougat/model.py", line 682, in from_pretrained
    model = super(NougatModel, cls).from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 3175, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 3624, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for NougatModel:
        size mismatch for encoder.model.layers.1.downsample.norm.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for encoder.model.layers.1.downsample.norm.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for encoder.model.layers.1.downsample.reduction.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([256, 512]).
        size mismatch for encoder.model.layers.2.downsample.norm.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for encoder.model.layers.2.downsample.norm.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for encoder.model.layers.2.downsample.reduction.weight: copying a param with shape torch.Size([1024, 2048]) from checkpoint, the shape in current model is torch.Size([512, 1024]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```

I suspect that this is related to nougat version, which turns out right:
this checkpoint error is gone after downgrading to nougat-ocr = 0.1.1

Query: How can I provide stable access to nougat ?

**Comment by lukas-blecher** [comment]
There hasn't really changed anything in that regard since 0.1.1
Is it only the first two layers of the swin encoder?

**Comment by binary-husky** [comment]
> There hasn't really changed anything in that regard since 0.1.1 Is it only the first two layers of the swin encoder?

sorry, I can only confirm the fact that sometimes I have to downgrade to make it work

**Comment by evdcush** [comment]
Same issue.
Latest: `nougat-ocr==0.1.8`

```
$ nougat --model 0.1.0-base --out ~/.cache ~/my_academic_document.pdf

Traceback (most recent call last):
  File "/home/foo/.pyenv/versions/3115/bin/nougat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/foo/.pyenv/versions/3.11.5/envs/3115/lib/python3.11/site-packages/predict.py", line 103, in main
    model = NougatModel.from_pretrained(args.checkpoint).to(torch.bfloat16)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/.pyenv/versions/3.11.5/envs/3115/lib/python3.11/site-packages/nougat/model.py", line 679, in from_pretrained
    model = super(NougatModel, cls).from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/.pyenv/versions/3.11.5/envs/3115/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3187, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/foo/.pyenv/versions/3.11.5/envs/3115/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3636, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for NougatModel:
	size mismatch for encoder.model.layers.1.downsample.norm.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.model.layers.1.downsample.norm.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.model.layers.1.downsample.reduction.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([256, 512]).
	size mismatch for encoder.model.layers.2.downsample.norm.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for encoder.model.layers.2.downsample.norm.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for encoder.model.layers.2.downsample.reduction.weight: copying a param with shape torch.Size([1024, 2048]) from checkpoint, the shape in current model is torch.Size([512, 1024]).
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```

**Comment by evdcush** [comment]
Thank you for your quick follow-up!

I decided to install Nougat via pip in a new venv:
(`pip install "nougat-ocr[api,dataset]"`)

I am no longer experiencing this shape error issue.

When installing Nougat in a different env, I noticed it was not using the latest `timm`. Latest (as of writing this) is `timm-0.9.7`; Nougat requires `timm-0.5.4`.

I A/B'd this `timm` version dep and can reproduce the shape mismatch error featured in this issue.

I believe I encountered this issue because I attempted to install and use Nougat in my default env that has the latest `timm`.

**Comment by binary-husky** [comment]
> cond

![image](https://github.com/facebookresearch/nougat/assets/96192199/229e81f3-ced2-4857-bd11-9cfea9409400)

**Comment by binary-husky** [comment]
> Thank you for your quick follow-up!
> 
> I decided to install Nougat via pip in a new venv: (`pip install "nougat-ocr[api,dataset]"`)
> 
> I am no longer experiencing this shape error issue.
> 
> When installing Nougat in a different env, I noticed it was not using the latest `timm`. Latest (as of writing this) is `timm-0.9.7`; Nougat requires `timm-0.5.4`.
> 
> I A/B'd this `timm` version dep and can reproduce the shape mismatch error featured in this issue.
> 
> I believe I encountered this issue because I attempted to install and use Nougat in my default env that has the latest `timm`.

*confirmed, this is the solution*, but can nougat upgrades to the latest timm?

**Comment by binary-husky** [comment]
As `timm` is also used by many other packages as well, it is reasonable to adopt its new APIs I think
