### ISSUE TITLE
OSError when Loading Pretrained Model: Missing config.json

### ISSUE THREAD

**Issue by tadeusER** [facebookresearch/nougat#80]
I encountered an issue while attempting to load a pretrained model named "nougat-0.1.0-small" using the Nougat library. The error message indicates that the config.json file is missing in the model cache directory /root/.cache/torch/hub/nougat-0.1.0-small. As a result, the loading process fails with an OSError.

error:
```
023-09-15 18:14:53.431388: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:root:No GPU found. Conversion on CPU is very slow.
downloading nougat checkpoint version None to path /root/.cache/torch/hub/nougat-0.1.0-small
config.json:  31% 9.00/29.0 [00:00<00:00, 33.5kb/s]
pytorch_model.bin:  31% 9.00/29.0 [00:00<00:00, 41.5kb/s]
special_tokens_map.json:  31% 9.00/29.0 [00:00<00:00, 41.0kb/s]
tokenizer.json:  31% 9.00/29.0 [00:00<00:00, 30.4kb/s]
tokenizer_config.json:  31% 9.00/29.0 [00:00<00:00, 38.6kb/s]
INFO:root:Output directory does not exist. Creating output directory.
Traceback (most recent call last):
  File "/usr/local/bin/nougat", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/predict.py", line 103, in main
    model = NougatModel.from_pretrained(args.checkpoint).to(torch.bfloat16)
  File "/usr/local/lib/python3.10/dist-packages/nougat/model.py", line 679, in from_pretrained
    model = super(NougatModel, cls).from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2530, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 591, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 675, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 400, in cached_file
    raise EnvironmentError(
OSError: /root/.cache/torch/hub/nougat-0.1.0-small does not appear to have a file named config.json. Checkout 'https://huggingface.co//root/.cache/torch/hub/nougat-0.1.0-small/main' for available files.
```

**Comment by erip** [comment]
You can work around this by adding `--model 0.1.0-small`. I'm not sure why it's needed, though.

**Comment by lukas-blecher** [comment]
Fixed now

**Comment by tadeusER** [comment]
> You can work around this by adding `--model 0.1.0-small`. I'm not sure why it's needed, though.

this solved my problem
